### ISSUE TITLE
Error on AMD cards

### ISSUE THREAD

**Issue by Menaxerius** [Creepsky/creepHash#1]
5:46:14 PM         Program.cs, 33   Unknown argument -U
5:46:21 PM  MultiMinerBase.cs, 287  Found hardware:
5:46:21 PM  MultiMinerBase.cs, 287  - Baffin, OpenCl
5:46:21 PM  MultiMinerBase.cs, 287  - Ellesmere, OpenCl
5:46:21 PM  MultiMinerBase.cs, 287  - Ellesmere, OpenCl
5:46:21 PM  MultiMinerBase.cs, 287  - Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz, OpenCl
5:46:21 PM  MultiMinerBase.cs, 235  Found miner:
5:46:21 PM  MultiMinerBase.cs, 235  - ccminer v.2.2.4
5:46:21 PM  MultiMinerBase.cs, 235  - ethminer v.0.14.0.dev2
5:46:21 PM  MultiMinerBase.cs, 319  Loaded benchmark files:
5:46:21 PM  MultiMinerBase.cs, 319  - ccminer v.2.2.4 with 0 benchmarked algorithm(s)
5:46:21 PM  MultiMinerBase.cs, 319  - ethminer v.0.14.0.dev2 with 0 benchmarked algorithm(s)
5:46:21 PM  MultiMinerBase.cs, 324  Benchmarking blake2s on Baffin, OpenCl with ccminer v.2.2.4
5:46:21 PM  MultiMinerBase.cs, 113  Could not start the mining instances
5:46:21 PM  MultiMinerBase.cs, 113  System.AggregateException: One or more errors occurred. (Could not run the mining instances) ---> System.Exception: Could not run the mining instances ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
5:46:21 PM  MultiMinerBase.cs, 113     at MultiCryptoToolLib.Common.HashRate.ToString() in E:\dev\C++\MultiCryptoTool\MultiCryptoToolLib\Common\HashRate.cs:line 90
5:46:21 PM  MultiMinerBase.cs, 113     at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
5:46:21 PM  MultiMinerBase.cs, 113     at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
5:46:21 PM  MultiMinerBase.cs, 113     at System.String.Format(String format, Object[] args)

**Comment by Menaxerius** [comment]
On a rig with AMD and Nvidia Cards mixed only the Nvidia Cards get shown, and they work, but the AMD cards won't do anything
